// src/lib/seed-data/default-module-definitions.ts
import type { Timestamp } from "firebase/firestore";

export interface ModuleDefinitionSeed {
  docId?: string; // Firestore document ID (optional, will be auto-generated if not provided, or used if provided)
  id: string; // Module slug
  name: string;
  description: string;
  icon: string;
  status: boolean;
  useSameColor: boolean;
  unifiedColor?: string;
  iconColor?: string;
  textColor?: string;
  color?: string; // Fallback/base color if specific ones aren't set
  parentId?: string;
  wasCreatedInImportMode?: boolean;
  imported?: boolean;
  isRichTextEditor?: boolean;
  canBeInitialPage?: boolean;
  canBeBottomBarItem?: boolean;
}

export const defaultModuleDefinitionsData: ModuleDefinitionSeed[] = [
  {
    id: "fast-smart-notes",
    name: "Fast Smart Notes",
    description: "Módulo para anotações rápidas e arquivamento, com foco em performance e funcionalidade offline.",
    icon: "Smile",
    status: true,
    useSameColor: true,
    unifiedColor: "#4CAF50",
    color: "#4CAF50",
    wasCreatedInImportMode: true,
    imported: true,
    canBeInitialPage: true,
    canBeBottomBarItem: true,
    parentId: "group-modules",
  },
  {
    id: "tiptap-editor",
    name: "Tip Tap Editor",
    description: "Editor de texto avançado (WYSIWYG) para criação de conteúdo rico.",
    icon: "PilcrowSquare",
    status: true,
    useSameColor: true,
    unifiedColor: "#3B82F6",
    color: "#3B82F6",
    wasCreatedInImportMode: false,
    imported: true,
    isRichTextEditor: true,
    parentId: "group-modules",
  },
    {
    id: "lexical-editor",
    name: "Lexical Editor",
    description: "Editor de texto avançado baseado no Lexical da Meta, com foco em performance e funcionalidades avançadas.",
    icon: "AudioLines",
    status: true,
    useSameColor: true,
    unifiedColor: "#1DA1F2",
    color: "#1DA1F2",
    wasCreatedInImportMode: false,
    imported: true,
    isRichTextEditor: true,
    parentId: "group-modules",
  },
  {
    id: "ai-module",
    name: "Integrações de IA",
    description: "Módulo para configurar e gerenciar integrações com APIs de Inteligência Artificial.",
    icon: "Brain",
    status: true,
    useSameColor: true,
    unifiedColor: "#8B5CF6",
    color: "#8B5CF6",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
    {
    id: "storage",
    name: "Armazenamento",
    description: "Gerencia as configurações dos diferentes gateways de armazenamento.",
    icon: "HardDrive",
    status: true,
    useSameColor: true,
    unifiedColor: "#F59E0B",
    color: "#F59E0B",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "payment",
    name: "Pagamentos",
    description: "Gerencia configurações de gateways e métodos de pagamento.",
    icon: "CreditCard",
    status: true,
    useSameColor: true,
    unifiedColor: "#22C55E",
    color: "#22C55E",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "invite",
    name: "Convites",
    description: "Gerencia o sistema de convites para acesso à aplicação.",
    icon: "MailPlus",
    status: true,
    useSameColor: true,
    unifiedColor: "#EF4444",
    color: "#EF4444",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
    canBeBottomBarItem: true,
  },
    {
    id: "transcription",
    name: "Transcrição de Áudio",
    description: "Fornece uma interface para configurar e testar serviços de transcrição de áudio.",
    icon: "Keyboard",
    status: true,
    useSameColor: true,
    unifiedColor: "#14B8A6",
    color: "#14B8A6",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "calc-genius",
    name: "Calc Genius",
    description: "Motor de cálculo genérico para consumir dados de diversas fontes e aplicar fórmulas customizadas.",
    icon: "Calculator",
    status: true,
    useSameColor: true,
    unifiedColor: "#A855F7",
    color: "#A855F7",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "pdf-generator",
    name: "Gerador de PDF",
    description: "Módulo centralizado para geração de documentos PDF.",
    icon: "FileText",
    status: true,
    useSameColor: true,
    unifiedColor: "#EC4899",
    color: "#EC4899",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "feed",
    name: "Feed",
    description: "Centraliza publicações internas e externas, permitindo integração social e interação.",
    icon: "Rss",
    status: true,
    useSameColor: true,
    unifiedColor: "#0EA5E9",
    color: "#0EA5E9",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "ai-text-assessor",
    name: "Assessor de Texto com IA",
    description: "Módulo para fornecer assistência de texto contextualizada por IA em toda a aplicação.",
    icon: "WandSparkles",
    status: true,
    useSameColor: true,
    unifiedColor: "#6366F1",
    color: "#6366F1",
    wasCreatedInImportMode: false,
    imported: true,
    parentId: "group-modules",
  },
  {
    id: "events",
    name: "Eventos",
    description: "Módulo para criar e gerenciar eventos em um calendário.",
    icon: "Calendar",
    status: true,
    useSameColor: true,
    unifiedColor: "#10B981",
    color: "#10B981",
    wasCreatedInImportMode: true,
    imported: true,
    canBeInitialPage: true,
    canBeBottomBarItem: true,
    parentId: "group-modules",
  },
  {
    id: "integrity-check",
    name: "Verificador de Integridade",
    description: "Serviço para assinar e verificar a integridade de arquivos gerados pelo sistema.",
    icon: "ShieldCheck",
    status: true,
    useSameColor: true,
    unifiedColor: "#334155",
    color: "#334155",
    wasCreatedInImportMode: true,
    imported: true,
    canBeInitialPage: true,
    parentId: "group-modules",
  }
];
